name: Grade Assignment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas matplotlib seaborn nbformat nbconvert jupyter_client jupyter ipykernel

    - name: Convert Jupyter Notebook to Python Script
      run: |
        jupyter nbconvert --to script climate_eda.ipynb --output climate_eda

    - name: Run the Python Script
      run: python climate_eda.py

    - name: Create Grade Summary
      run: |
        echo "## Assignment Completed Successfully" > grade_summary.md

    - name: Upload Grade Summary
      uses: actions/upload-artifact@v4
      with:
        name: grade-summary
        path: grade_summary.md
